from enum import StrEnum


class VectorStatus(StrEnum):
    PENDING = "PENDING"
    INDEXED = "INDEXED"
    FAILED = "FAILED"


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MODIFIED = "MODIFIED"
    MERGED = "MERGED"


class CandidateSource(StrEnum):
    LLM = "LLM"
    FAKE = "FAKE"
    MANUAL = "MANUAL"


class AuditAction(StrEnum):
    EXTRACTION_RUN = "EXTRACTION_RUN"
    ENTITY_APPROVED = "ENTITY_APPROVED"
    ENTITY_REJECTED = "ENTITY_REJECTED"
    ENTITY_MODIFIED = "ENTITY_MODIFIED"
    ENTITY_MERGED = "ENTITY_MERGED"
    RELATION_APPROVED = "RELATION_APPROVED"
    RELATION_REJECTED = "RELATION_REJECTED"
    RELATION_MODIFIED = "RELATION_MODIFIED"
    RELATION_MERGED = "RELATION_MERGED"


SCHEMA_VIOLATION_UNKNOWN_ENTITY = "SCHEMA_VIOLATION: unknown entity type"
SCHEMA_VIOLATION_RELATION_NOT_ALLOWED = (
    "SCHEMA_VIOLATION: relation not allowed for given source/target types"
)


class GraphSyncTargetType(StrEnum):
    ENTITY = "ENTITY"
    RELATION = "RELATION"


class GraphSyncStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
